### ISSUE TITLE
'make html' shows error 

### ISSUE THREAD

**Issue by ralphjzhang** [rcore-os/rCore-Tutorial-Book-v3#127]
Sphinx error:
master file /home/zhjun/Book/rCore-Tutorial-Book-v3/source/contents.rst not found
make: *** [Makefile:20: html] Error 2

**Comment by wyfcyx** [comment]
What is the Sphinx version?

**Comment by ralphjzhang** [comment]
> 

sphinx-build 1.8.5

**Comment by wyfcyx** [comment]
Please upgrade to version >=4.0.0.

**Comment by ralphjzhang** [comment]
works great! thanks!
