### ISSUE TITLE
第一章正确进展缺的一些前期配置

### ISSUE THREAD

**Issue by chyyuu** [rcore-os/rCore-Tutorial-Book-v3#2]
···
rustup component add rust-src 
rustup component add llvm-tools-preview
cargo install cargo-binutils
rustup target add riscv64gc-unknown-none-elf
···
请看看应该加在哪里

**Comment by wyfcyx** [comment]
在[旧版的环境配置](https://rcore-os.github.io/rCore-Tutorial-deploy/docs/pre-lab/env.html)的**安装完成后**一小节提到了这部分配置，但确实不够清晰。我最近应该会参照旧版把环境配置这一小节重写一遍，去除旧版的依赖。

**Comment by wyfcyx** [comment]
环境配置章节已经重写，上述配置也加到了框架中。
