### ISSUE TITLE
第二章批处理：特权级的切换部分 缺少图解

### ISSUE THREAD

**Issue by LebranceBW** [rcore-os/rCore-Tutorial-Book-v3#60]
RT
我最近在看这部分看了好久，特别是trap/trap.S部分，很难理解异常处理过程。因此，我想给这部分补一张中断\异常处理时的栈变化情况图。:smile:。我会提一个PR，还希望能帮我看看，我滴理解有没有问题。

**Comment by wyfcyx** [comment]
多谢！等有时间我看看如何插入进来。

**Comment by LebranceBW** [comment]
> 多谢！等有时间我看看如何插入进来。

你好，我已经绘制了两张图。然后补充了一个例子，已经提交了PR。你可以看一下 #61
