### ISSUE TITLE
关于ch4练习的一个问题，能不能说一下思路或者答案

### ISSUE THREAD

**Issue by kaifoon** [rcore-os/rCore-Tutorial-Book-v3#62]
缺页的另一个常见原因是 swap 策略，也就是内存页面可能被换到磁盘上了，导致对应页面失效。
此时页面失效如何表现在页表项(PTE)上？

**Comment by wyfcyx** [comment]
@kaifoon 在内核中需要有数据结构记录每个进程的地址空间中所有会用到的虚拟页面的情况，这样才能实现全局/局部页面替换算法。将一个页面换出到磁盘的时候，一种可能的实现是：将对应页表项的Valid位和PPN字段清零（这将会导致下次访问时触发Page Fault），将当前所在物理页帧上的数据拷贝到磁盘上的一个位置，而后在数据结构中记录该页面的数据在磁盘上的哪个位置。这样换入的时候可以从数据结构中查到数据在磁盘上的位置，然后复制到本次空出来的物理页帧上面。

**Comment by kaifoon** [comment]
谢谢，明白了
