### ISSUE TITLE
页面评论无法加载，F12 可以看到 sphinx_comments 插件找不到选择器，可能是 Sphinx、sphinx_rtd_theme 升级后页面结构改变导致的

### ISSUE THREAD

**Issue by vcheckzen** [rcore-os/rCore-Tutorial-Book-v3#91]
https://github.com/executablebooks/sphinx-comments/blob/28b946ea9dc52f8ef87b4428ff59aea4224d639a/sphinx_comments/__init__.py#L80-L84

**Comment by wyfcyx** [comment]
非常感谢！之前一直不清楚到底为什么加载不出来讨论区，目前总算是暂时修好了。不过似乎与这些软件的版本没有关系，好像是因为我在国外所以构建出来的页面结构有问题？这我就不清楚了。
